platform:
  base-url: "https://kovan.cloud.enjin.io/"
  app:
    id: -1
    secret: ""
    dev-address: ""
locale: "en_US"
debug:
  sdk: false
  plugin: false
  sentry: ""
experimental:
  translate-console-messages: false
interal:
  config-version: 1
permission-blacklist:
  - "minecraft.command.op"
  - "minecraft.command.deop"
  - "minecraft.command.stop"
# link-permissions:
#   - "example.perm1"
#   - "example.perm2"
